headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/Users/joelburlin/dev/mac-rec/docs"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/download"
to = "https://github.com/joelburlin/mac-rec/releases/latest/download/Mac-Rec-0.4.0.dmg"
status = 302.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/github"
to = "https://github.com/joelburlin/mac-rec"
status = 302.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/skill"
to = "https://github.com/joelburlin/mac-rec/blob/main/skills/mac-rec/SKILL.md"
status = 302.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]